spring:
  redis:
    host: 127.0.0.1                # Redis服务器地址
    port: 6379                     # Redis服务器连接端口
    database: 0                    # Redis数据库索引（默认为0）
    timeout: 5000                  # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20             # 接池最大连接数（使用负值表示没有限制）
        max-wait: -1               # 最大阻塞等待时间(负数表示没限制)
        max-idle: 5                # 连接池中的最大空闲连接
        min-idle: 0                # 连接池中的最小空闲连接
